export type StudentScheduleItem = {
  id: string;
  tutorId: string;
  tutorInitials: string;
  tutorName: string;
  subject: string;
  date: string;
  time: string;
  duration: string;
  type: "Virtual" | "In-Person";
  status: "Upcoming" | "Completed" | "Cancelled";
  fullDate: string;
  sessionRate: number;
  chat: Array<{
    id: string;
    sender: "tutor" | "student";
    message: string;
    timestamp: string;
  }>;
};

export const studentScheduleItems: StudentScheduleItem[] = [
  {
    id: "s1",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Algebra II",
    date: "Mon, Mar 30",
    time: "4:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Upcoming",
    fullDate: "Monday, March 30, 2026",
    sessionRate: 45,
    chat: [
      {
        id: "m1",
        sender: "tutor",
        message:
          "Hi Jordan! Looking forward to our session on Monday. Do you have any specific topics you'd like to focus on in Algebra II?",
        timestamp: "Mon 10:22 AM",
      },
      {
        id: "m2",
        sender: "student",
        message:
          "Hey! Yes, I'm struggling with polynomial functions and factoring. Can we start there?",
        timestamp: "Mon 11:05 AM",
      },
      {
        id: "m3",
        sender: "tutor",
        message:
          "Absolutely! Polynomial factoring is a great topic to solidify. I'll prepare some examples and practice problems. See you Monday at 4 PM!",
        timestamp: "Mon 11:30 AM",
      },
    ],
  },
  {
    id: "s2",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "English Literature",
    date: "Wed, Apr 1",
    time: "3:30 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Upcoming",
    fullDate: "Wednesday, April 1, 2026",
    sessionRate: 40,
    chat: [
      {
        id: "m4",
        sender: "tutor",
        message: "Let's use our next session to review your literary analysis outline and thesis clarity.",
        timestamp: "Tue 4:15 PM",
      },
    ],
  },
  {
    id: "s3",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Biology",
    date: "Fri, Apr 3",
    time: "5:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Upcoming",
    fullDate: "Friday, April 3, 2026",
    sessionRate: 40,
    chat: [
      {
        id: "m5",
        sender: "tutor",
        message: "We can spend the first half on cell transport and the second half on practice questions.",
        timestamp: "Wed 6:10 PM",
      },
    ],
  },
  {
    id: "s4",
    tutorId: "104",
    tutorInitials: "DL",
    tutorName: "Derek Lewis",
    subject: "ACT/SAT Prep",
    date: "Mon, Mar 23",
    time: "6:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Monday, March 23, 2026",
    sessionRate: 55,
    chat: [],
  },
  {
    id: "s5",
    tutorId: "105",
    tutorInitials: "KW",
    tutorName: "Karen Wright",
    subject: "Reading",
    date: "Wed, Mar 18",
    time: "4:00 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
    fullDate: "Wednesday, March 18, 2026",
    sessionRate: 28,
    chat: [],
  },
  {
    id: "s6",
    tutorId: "106",
    tutorInitials: "JM",
    tutorName: "James Morgan",
    subject: "U.S. History",
    date: "Tue, Mar 10",
    time: "5:30 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Tuesday, March 10, 2026",
    sessionRate: 42,
    chat: [],
  },
  {
    id: "s7",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Geometry",
    date: "Thu, Mar 12",
    time: "4:30 PM",
    duration: "45 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Thursday, March 12, 2026",
    sessionRate: 35,
    chat: [],
  },
  {
    id: "s8",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "Essay Writing",
    date: "Fri, Mar 6",
    time: "3:00 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
    fullDate: "Friday, March 6, 2026",
    sessionRate: 40,
    chat: [],
  },
  {
    id: "s9",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Chemistry",
    date: "Mon, Feb 24",
    time: "5:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Monday, February 24, 2026",
    sessionRate: 40,
    chat: [],
  },
  {
    id: "s10",
    tutorId: "104",
    tutorInitials: "DL",
    tutorName: "Derek Lewis",
    subject: "Statistics",
    date: "Tue, Mar 17",
    time: "6:30 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Tuesday, March 17, 2026",
    sessionRate: 55,
    chat: [],
  },
  {
    id: "s11",
    tutorId: "105",
    tutorInitials: "KW",
    tutorName: "Karen Wright",
    subject: "Phonics",
    date: "Thu, Feb 20",
    time: "3:30 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
    fullDate: "Thursday, February 20, 2026",
    sessionRate: 28,
    chat: [],
  },
  {
    id: "s12",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Algebra I",
    date: "Tue, Feb 11",
    time: "4:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Tuesday, February 11, 2026",
    sessionRate: 45,
    chat: [],
  },
  {
    id: "s13",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "Writing",
    date: "Mon, Jan 27",
    time: "3:30 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
    fullDate: "Monday, January 27, 2026",
    sessionRate: 40,
    chat: [],
  },
  {
    id: "s14",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Biology",
    date: "Wed, Jan 15",
    time: "5:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Wednesday, January 15, 2026",
    sessionRate: 40,
    chat: [],
  },
  {
    id: "s15",
    tutorId: "104",
    tutorInitials: "DL",
    tutorName: "Derek Lewis",
    subject: "Math",
    date: "Thu, Jan 9",
    time: "7:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Thursday, January 9, 2026",
    sessionRate: 55,
    chat: [],
  },
  {
    id: "s16",
    tutorId: "105",
    tutorInitials: "KW",
    tutorName: "Karen Wright",
    subject: "Literacy",
    date: "Fri, Jan 3",
    time: "4:15 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Completed",
    fullDate: "Friday, January 3, 2026",
    sessionRate: 28,
    chat: [],
  },
  {
    id: "s17",
    tutorId: "106",
    tutorInitials: "JM",
    tutorName: "James Morgan",
    subject: "AP History",
    date: "Wed, Mar 11",
    time: "1:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Wednesday, March 11, 2026",
    sessionRate: 42,
    chat: [],
  },
  {
    id: "s18",
    tutorId: "101",
    tutorInitials: "MT",
    tutorName: "Marcus Thompson",
    subject: "Algebra II",
    date: "Fri, Mar 13",
    time: "4:00 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Completed",
    fullDate: "Friday, March 13, 2026",
    sessionRate: 45,
    chat: [],
  },
  {
    id: "s19",
    tutorId: "102",
    tutorInitials: "SA",
    tutorName: "Sandra Avery",
    subject: "English",
    date: "Tue, Mar 24",
    time: "5:15 PM",
    duration: "45 min",
    type: "In-Person",
    status: "Cancelled",
    fullDate: "Tuesday, March 24, 2026",
    sessionRate: 40,
    chat: [],
  },
  {
    id: "s20",
    tutorId: "103",
    tutorInitials: "RJ",
    tutorName: "Rebecca Jones",
    subject: "Earth Science",
    date: "Thu, Mar 26",
    time: "4:45 PM",
    duration: "60 min",
    type: "Virtual",
    status: "Cancelled",
    fullDate: "Thursday, March 26, 2026",
    sessionRate: 40,
    chat: [],
  },
];

export function getStudentScheduleItemById(id: string) {
  return studentScheduleItems.find((item) => item.id === id);
}
